# Backup server parameters
local_files_port: 4444 # TCP/IP port to start server to send files to backup.
local_content_data_port: 3333 # TCP/IP port to start server to send content data upon request from client.

# Local files and logs
log_file_name: '~/.bbfs/log/content_server.log4r' # General log
default_monitoring_log_path: '~/.bbfs/log/content_file_monitoring.log' # Log for file changes
local_content_data_path: '~/.bbfs/var/content.data' # File to store all contents, i.e., state of content server.

# Logging options
log_write_to_console: true # Will print all log messages to standard output. Default is false.
log_write_to_email: true # Will print error and fatal log messages to email output. Default is false.
log_debug_level: 0 # Verbosity of logging. 0 will log only INFO messages. Other value, will log all
                   # DEBUG messages as well.
from_email: 'bbfsdev@gmail.com' # From gmail address for update
from_email_password: 'enter your password here' # From gmail password
to_email: 'bbfsdev@gmail.com' # Destination email for updates

# Configuration for the file monitoring module.
# This module go over a directory, and monitor all sub files and directories.
monitoring_paths:
  - path: '~/.bbfs/test_files' # Directory to monitor.
    scan_period: 1 # Number of seconds before initiating another directory scan.
    stable_state: 5 # Number of scan times for a file to be unchanged before his state becomes stable.
  - path: '~/.bbfs/test_files2' # Another directory
    scan_period: 3
    stable_state: 7

