############# START OF FILE #################
#Backup server parameters
content_server_hostname: 'localhost' # Default is nil
content_server_files_port: 4444 # TCP/IP port to start server to send files to backup.
# TCP/IP port to start server to send content data upon request from client.
content_server_data_port: 3333
#backup data file, i.e. state(index) of backup server destination folder.
local_content_data_path: '~/.bbfs/var/backup.data' # File to store content data

# Path to backup files from master and to monitor
backup_destination_folder:
  - path: '~/.bbfs/backup_files' # Directory to monitor.
    scan_period: 5 # Number of seconds before initiating another directory scan.
    stable_state: 1 # Number of scan times for a file to be unchanged before his state becomes stable.

# Paths to monitor directories. All path files and recursive sub paths are used.
monitoring_paths:
  - path: '~/.bbfs/monitor_local_files'
    scan_period: 1 # Number of seconds before initiating another directory scan.
    stable_state: 5 # Number of scan times for a file to be unchanged before his state becomes stable.

#cycles of fetch period used by backup server to ping content server for its content
remote_content_save_timeout: 120

#Cycles where backup is checking if sync is required between remote and backup contents
backup_check_delay: 60

#Cycles where server write the content data to a local file
data_flush_delay: 60

######process variables monitoring parameters
enable_monitoring: true
#Browing on server:port will show the varialbes
process_monitoring_web_port: 5555
#Cycles(seconds) to update variables
process_vars_delay: 15

#Logging options
log_write_to_file: true # Will print all log messages to file
log_file_name: '~/.bbfs/log/backup_server.log4r'
log_write_to_console: true # Will print all log messages to standard output. Default is false.
log_write_to_email: true # Will print errors to mail on system crush only . Default is false.
# Verbosity of logging. 0 will log INFO messages. 3 will print ALL debug messages as well.
log_debug_level: 0
from_email: 'jhon.doe@gmail.com'  # user should change to real value
from_email_password: 'hihahu'  # user should change to real value
to_email: 'jhon.doe@gmail.com'  # user should change to real value
default_monitoring_log_path: '~/.bbfs/log/backup_file_monitoring.log' # Log of file changes

# print all parameters to console at the beginning of execution log.
print_params_to_stdout: true
############# END OF FILE #################
