# Content server parameters
content_server_hostname: 'localhost' #'f1.test.kbb1.com' # Default is nil
content_server_files_port: 4444 # TCP/IP port to connect as client to receive files to backup from content server.
content_server_data_port: 3333 # TCP/IP port to connect as client to get content data.

# Local files and logs
log_file_name: '~/.bbfs/log/backup_server.log' # General log
default_monitoring_log_path: '~/.bbfs/log/backup_file_monitoring.log' # Log for file changes
local_content_data_path: '~/.bbfs/var/backup.data' # File to store all local contents, i.e., backed up files.

# Logging options
log_write_to_console: true # Will print all log messages to standard output. Default is false.
log_debug_level: 0 # Verbosity of logging. Default is 0, max is 3.
from_email: 'bbfsdev@gmail.com' # gmail account to send updates  
from_email_password: 'enter your password here' # password of gmail account to send updates  

# Configuration for the file monitoring module.
# This module go over a directory, and monitor all sub files and directories.
# In backup server only one directory of the backed up files should be monitored!
monitoring_paths:
  - path: '~/.bbfs/backup_files' # Directory to monitor.
    scan_period: 1 # Number of seconds before initiating another directory scan.
    stable_state: 5 # Number of scan times for a file to be unchanged before his state becomes stable.


