### Generated by rprotoc. DO NOT EDIT!
### <proto file: agent.proto>
# /**
#  * Created by IntelliJ IDEA.
#  * User: genadyp
#  * Date: 11/30/11
#  * Time: 7:54 AM
#  * To change this template use File | Settings | File Templates.
#  */
# 
# import "content_data.proto";
# 
# message IndexerPatternsMessage {
#     repeated string positive_patterns = 1;
#     repeated string negative_patterns = 2;
# }
# 
# message IndexerArgumentsMessage {
#     optional IndexerPatternsMessage patterns = 1;
#     optional ContentDataMessage otherDB = 2;
# }
# 
# service AgentService {
#     rpc Index (IndexerArgumentsMessage) returns (ContentDataMessage);
# }
require 'protobuf/message/message'
require 'protobuf/message/enum'
require 'protobuf/message/service'
require 'protobuf/message/extend'

require './content_data.pb'
class IndexerPatternsMessage < ::Protobuf::Message
  defined_in __FILE__
  repeated :string, :positive_patterns, 1
  repeated :string, :negative_patterns, 2
end
class IndexerArgumentsMessage < ::Protobuf::Message
  defined_in __FILE__
  optional :IndexerPatternsMessage, :patterns, 1
  optional :ContentDataMessage, :otherDB, 2
end